import React from 'react';
import { Card } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';

export default function Pricing() {
  const tiers = [
    {
      name: 'Citizen',
      price: 'Free',
      description: 'Start your journey',
      features: [
        'Digital Twin',
        'Memory Graph (basic)',
        'HOPE AI Companion',
        'Community Access',
        'Basic Analytics',
        'Max 2 AI Agents',
      ],
      cta: 'Get Started',
      highlighted: false,
    },
    {
      name: 'Builder',
      price: '$9.99',
      period: '/month',
      description: 'Create & earn',
      features: [
        'Everything in Citizen',
        'Creator Tools',
        'Max 10 AI Agents',
        'Advanced Memory Graph',
        'Startup Generator',
        'Revenue Sharing (5%)',
        'Priority Support',
      ],
      cta: 'Start Free Trial',
      highlighted: true,
    },
    {
      name: 'Scalable',
      price: 'Custom',
      description: 'Scale your impact',
      features: [
        'Everything in Builder',
        'Unlimited AI Agents',
        'API Access',
        'Custom Integrations',
        'Dedicated Account Manager',
        'Revenue Sharing (10%)',
        'SLA Support',
      ],
      cta: 'Contact Sales',
      highlighted: false,
    },
  ];

  return (
    <div className="min-h-screen bg-black text-white p-8">
      <div className="max-w-7xl mx-auto">
        <div className="text-center mb-16">
          <h1 className="text-5xl font-bold mb-4">Simple, Transparent Pricing</h1>
          <p className="text-xl text-gray-400">Choose the plan that fits your journey</p>
        </div>

        <div className="grid grid-cols-3 gap-8 mb-16">
          {tiers.map((tier) => (
            <Card
              key={tier.name}
              className={`p-8 flex flex-col ${
                tier.highlighted
                  ? 'bg-gradient-to-b from-cyan-900 to-gray-900 border-cyan-500 ring-2 ring-cyan-500'
                  : 'bg-gray-900 border-gray-800'
              }`}
            >
              {tier.highlighted && (
                <Badge className="w-fit mb-4 bg-cyan-600">Most Popular</Badge>
              )}
              <h3 className="text-2xl font-bold mb-2">{tier.name}</h3>
              <p className="text-gray-400 text-sm mb-6">{tier.description}</p>

              <div className="mb-6">
                <span className="text-4xl font-bold">{tier.price}</span>
                {tier.period && <span className="text-gray-400">{tier.period}</span>}
              </div>

              <Button
                className={`w-full mb-8 ${
                  tier.highlighted
                    ? 'bg-cyan-600 hover:bg-cyan-700'
                    : 'bg-gray-700 hover:bg-gray-600'
                }`}
              >
                {tier.cta}
              </Button>

              <div className="space-y-4 flex-1">
                {tier.features.map((feature) => (
                  <div key={feature} className="flex items-start">
                    <span className="text-cyan-400 mr-3">✓</span>
                    <span className="text-sm">{feature}</span>
                  </div>
                ))}
              </div>
            </Card>
          ))}
        </div>

        {/* FAQ */}
        <div className="max-w-3xl mx-auto">
          <h2 className="text-3xl font-bold mb-8 text-center">Frequently Asked Questions</h2>
          <div className="space-y-6">
            {[
              {
                q: 'Can I upgrade or downgrade anytime?',
                a: 'Yes, you can change your plan at any time. Changes take effect immediately.',
              },
              {
                q: 'What payment methods do you accept?',
                a: 'We accept all major credit cards, PayPal, and SKY444 tokens.',
              },
              {
                q: 'Is there a free trial for paid plans?',
                a: 'Yes, all paid plans include a 14-day free trial. No credit card required.',
              },
              {
                q: 'What does Revenue Sharing mean?',
                a: 'Earn a percentage of revenue generated by your AI agents, creators, or apps.',
              },
            ].map((item, i) => (
              <Card key={i} className="bg-gray-900 border-gray-800 p-6">
                <h4 className="font-bold mb-2">{item.q}</h4>
                <p className="text-gray-400">{item.a}</p>
              </Card>
            ))}
          </div>
        </div>
      </div>
    </div>
  );
}
