export const ACTION_TYPES = {
  PAYMENT: "PAYMENT",
  TIP: "TIP",
  REQUEST_SERVICE: "REQUEST_SERVICE",
  CREATE_LISTING: "CREATE_LISTING",
  MATCH_USER: "MATCH_USER",
  CALL_AI_AGENT: "CALL_AI_AGENT",
  SCHEDULE_EVENT: "SCHEDULE_EVENT",
} as const;

export type ActionType = (typeof ACTION_TYPES)[keyof typeof ACTION_TYPES];
